name: Deploy to EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: JDK 설정
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Gradle 권한 부여
        run: chmod +x ./gradlew

      - name: Spring Boot 애플리케이션 빌드
        run: ./gradlew build
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USER_NAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}

      - name: Check build artifacts
        run: ls -R build/libs

      - name: 빌드된 JAR 파일을 EC2로 복사
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: "build/libs/board-0.0.1-SNAPSHOT.jar"
          target: "/home/ubuntu"
          strip_components: 2

      - name: EC2에 접속해서 배포 스크립트 실행
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            pgrep java | xargs kill -9
            nohup java -jar -Dspring.profiles.active=prod /home/ubuntu/*.jar > /home/ubuntu/application.log 2>&1 &